/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.IOException;
import java.net.Socket;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class formSeleccion extends javax.swing.JFrame {

    private Socket Servidor;
    private PublicKey ClavePublica;
    private PrivateKey ClavePrivada;
    
    public formSeleccion(int rol, Socket Servidor, PublicKey clavePublica, PrivateKey claveprivada){
        initComponents();
        this.Servidor = Servidor;
        if (rol != 0){
            this.btnGestionarDatos.setEnabled(true);
            this.btnRegiones.setEnabled(true);
        } else{
            this.btnGestionarDatos.setEnabled(true);
            this.btnRegiones.setEnabled(true);
            this.btnGestionarUsuarios.setEnabled(true);
        }
               
    }
    
    public formSeleccion(Socket Servidor) {
        initComponents();
        this.Servidor = Servidor;
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDatos = new javax.swing.JButton();
        btnRegiones = new javax.swing.JButton();
        btnGestionarDatos = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDatos.setText("Consultar Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnRegiones.setText("Gestionar regiones (Gestor/administrador)");
        btnRegiones.setEnabled(false);
        btnRegiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionesActionPerformed(evt);
            }
        });

        btnGestionarDatos.setText("Gestionar datos (Gestor/Administrador)");
        btnGestionarDatos.setEnabled(false);
        btnGestionarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarDatosActionPerformed(evt);
            }
        });

        btnGestionarUsuarios.setText("Gestiona usuarios(SOLO Administradores)");
        btnGestionarUsuarios.setEnabled(false);
        btnGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuariosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuariosActionPerformed
        try {
            Utiles.Utiles.enviarObjeto(Servidor, 3);
            Utiles.Utiles.enviarObjeto(Servidor, this.ClavePublica);
            formRegiones regiones = new formRegiones(this.Servidor, this.ClavePublica, this.ClavePrivada, this);
            regiones.setVisible(true);
            this.setVisible(false);
            
        } catch (IOException ex) {
            Logger.getLogger(formSeleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGestionarUsuariosActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        try {
            Utiles.Utiles.enviarObjeto(Servidor, 0);
            formConsultar consulta = new formConsultar(this.Servidor, this);
            consulta.show();
            this.hide();          
        } catch (IOException ex) {
            Logger.getLogger(formSeleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnRegionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionesActionPerformed
        try {
            Utiles.Utiles.enviarObjeto(Servidor, 1);
            formRegiones regiones = new formRegiones(this.Servidor, this.ClavePublica, this.ClavePrivada, this);
            regiones.show();
            this.hide();
            
        } catch (IOException ex) {
            Logger.getLogger(formSeleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegionesActionPerformed

    private void btnGestionarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarDatosActionPerformed
        try {
            Utiles.Utiles.enviarObjeto(Servidor, 2);
            formDatos datos = new formDatos(this.Servidor, this.ClavePublica, this.ClavePrivada, this);
            datos.show();
            this.hide();
            
            
        } catch (IOException ex) {
            Logger.getLogger(formSeleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGestionarDatosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            Utiles.Utiles.enviarObjeto(Servidor, 4);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(formSeleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnGestionarDatos;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JButton btnRegiones;
    private javax.swing.JButton btnSalir;
    // End of variables declaration//GEN-END:variables
}
